import json
import shutil
import os

# ==========================
# Load Draft Graph
# ==========================

DRAFT_FILE = "graph_output.json"      # Generated by test_pipeline.py
MAIN_FILE = "graph_main.json"         # Simulated Main Branch

if not os.path.exists(DRAFT_FILE):
    print(f"❌ {DRAFT_FILE} not found.")
    print("Run 'python test_pipeline.py' first.")
    exit()

with open(DRAFT_FILE, "r", encoding="utf-8") as f:
    graph = json.load(f)

# ==========================
# Display Draft Graph
# ==========================

print("\n" + "=" * 70)
print("        HUMAN-IN-THE-LOOP (HITL) REVIEW")
print("=" * 70)

print("\n📌 NODES\n")

for i, node in enumerate(graph["nodes"], start=1):
    print(f"{i}. {node['label']}")
    print(f"   ID         : {node['id']}")
    print(f"   Properties : {node['properties']}")
    print()

print("=" * 70)

print("\n🔗 RELATIONSHIPS\n")

for i, edge in enumerate(graph["edges"], start=1):
    print(
        f"{i}. {edge['source']} "
        f"--[{edge['relation']}]--> "
        f"{edge['target']}"
    )

print("\n" + "=" * 70)

# ==========================
# Review Decision
# ==========================

choice = input("\nApprove Draft Graph? (y/n): ").strip().lower()

if choice == "y":

    shutil.copyfile(DRAFT_FILE, MAIN_FILE)

    print("\n✅ Graph Approved")
    print("✅ Draft merged into MAIN")
    print(f"✅ Main graph saved as '{MAIN_FILE}'")

else:

    print("\n❌ Graph Rejected")
    print("❌ Draft NOT merged into MAIN")

print("\nPipeline Finished.")